post http://localhost:4000/user-api/user
Content-Type: application/json

{   
    "userType":"user",
    "username":"hari",
    "password":"hari",
    "email":"hari@mail.com"
}

###
post http://localhost:4000/author-api/user
Content-Type: application/json

{
    "userType":"author",
    "username":"ravi",
    "password":"ravi",
    "email":"ravi@mail.com"
}


###
post http://localhost:4000/user-api/login
Content-Type: application/json


{
    "userType":"user",
    "username":"hari",
    "password":"hari"
}

###
post http://localhost:4000/author-api/login
Content-Type: application/json

{
    "userType":"author",
    "username":"ravi",
    "password":"ravi"
}

###

post http://localhost:4000/author-api/new-article
Content-Type: application/json

{
    "articleId":"{{$timestamp}}",
    "title":"Fundamentals of JS",
    "category":"programming",
    "content":"JavaScript is a high-level programming language that follows the ECMAScript standard. It was originally designed as a scripting language for websites but became widely adopted as a general-purpose programming language, and is currently the most popular programming language in use. JavaScript is usually found running in a web browser as interactive or automated content, ranging from popup messages and live clocks to large web applications. JavaScript is also commonly used in server-side programming through platforms like Node.js",
    "dateOfCreation":"{{$datetime iso8601}}",
    "dateOfModification":"{{$datetime iso8601}}",
    "username":"ravi",
    "comments":[],
    "status":true
}

###

get http://localhost:4000/author-api/articles/ravi